import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-light-gray font-karla flex h-screen items-center justify-center">
        {children}
      </body>
    </html>
  )
}
